### PR TITLE
added .env file template

### LINKED ISSUE #7: Add .env example to backend directory
### Add .env example to backend directory

On **_/tavern/tavern-backend/_**, .**env** file example is not yet added. Please create and add the following variables to the **.env** file

Expected result **/tavern/tavern-backend/.env**
```.env
APP_VERSION = ''
APP_TITLE = ''
APP_DESCRIPTION = ''
APP_URL = ''
APP_PORT = ''
APP_DEBUG = True
APP_SECRET_KEY = ''

MONGO_ROOT_USER = ''
MONGO_ROOT_PASSWORD = ''
MONGO_DATABASE = ''
MONGO_COLLECTION = ''

MONGOEXPRESS_LOGIN = ''
MONGOEXPRESS_PASSWORD = ''
```

**NOTES:** 

- Please create a PR to the **dev** branch
- Follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### PR DESCRIPTION
**Pull request by kaustav202**
fixes #7

### CODE REVIEW

**Comment by nat236919** [comment]
@kaustav202 Thanks, looking good. Would you mind using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for your commit message?

**Ex.)** chore: create .env file example

**Review by nat236919 — CHANGES_REQUESTED** [review]
@kaustav202 Thanks, looking good. Would you mind using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for your commit message?

**Ex.)** 

- chore: create .env file example

**Comment by kaustav202** [comment]
updated the commit message @nat236919

**Review by nat236919 — APPROVED** [review]
LGTM

**Pull request merged**
